# Generated by Django 4.1.2 on 2022-10-17 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('order', models.SmallIntegerField(unique=True, verbose_name='Порядок')),
                ('access', models.BooleanField(default=True, verbose_name='Доступ')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставка',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=13, verbose_name="Ім'я")),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('city', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('address', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('post_code', models.CharField(max_length=5)),
                ('commentary', models.TextField(verbose_name='Коментарій')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата і час створення')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата і час оновлення')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='order.posttype', verbose_name='Доставка')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ('time_update', 'time_create'),
            },
        ),
    ]
