# Generated by Django 4.1.2 on 2022-10-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.TextField(default='', verbose_name='Замовлення'),
        ),
    ]
