# Generated by Django 4.1.2 on 2022-10-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'На огляді'), ('verify', 'Перевірений'), ('sent', 'Відправлено'), ('completed', 'Завершено')], default='open', max_length=10, verbose_name='Статус замовлення'),
        ),
    ]
